kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "allow-nodeport-{{.Release.Name}}"
spec:
  podSelector:
   matchLabels:
    app: "{{.Release.Name}}"
  policyTypes:
  ingress:
    - ports:
      - protocol: TCP
        port: 8080
  egress:
    - ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
